dist: xenial
language: node_js
node_js:
- '7'
branch:
  only:
    - openmrs
script: npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: openmrs
  local_dir: dist
  fqdn: radar.openmrs.org
  name: Burke Mamlin
  email: burke@openmrs.org
